version: 0.0.1
dbConnection:
    type: postgres
    database: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
migrations: 
  - id: 001_initial
    applyPath: migrations/001_initial.sql
    rollbackPath: migrations/001_initial_rollback.sql
apiPath: ../mark-api.yaml

methodPaths:
  /public/article:
    get:
      path: queries/article/public/pget-articles.yaml
  /regular-user/article:
    get:
      path: queries/article/regular-user/r-aget-articles.yaml
    post:
      path: queries/article/regular-user/r-aadd-article.yaml
  /regular-user/article/{id}:
    put:
      path: queries/article/regular-user/r-aupdate-article.yaml
    delete:
      path: queries/article/regular-user/r-adelete-article.yaml
  /regular-user/event:
    get:
      path: queries/event/regular-user/r-aget-events.yaml
  /regular-user/me:
    get:
      path: queries/user/regular-user/r-amy-profile.yaml
  /regular-user/goodstanding:
    get:
      path: queries/user/regular-user/r-adownload-good-standing.yaml
  /regular-user/me/lodge:
    get:
      path: queries/user/regular-user/r-amy-lodges.yaml
  /regular-user/history:
    get:
      path: queries/user/regular-user/r-amy-history.yaml
  /regular-user/contribution:
    get:
      path: queries/user/regular-user/r-amy-contributions.yaml
  /regular-user/payment:
    get:
      path: queries/user/regular-user/r-amy-payments.yaml
    post:
      path: queries/user/regular-user/r-aadd-payment.yaml
  /regular-user/rsvp/{code}:
    put:
      path: queries/event/regular-user/r-arsvp-event.yaml
  /regular-user/lodge:
    get:
      path: queries/lodge/regular-user/r-aget-lodges.yaml
  /lodge-admin/article:
    get:
      path: queries/article/lodge-admin/l-aget-articles.yaml
    post:
      path: queries/article/lodge-admin/l-aadd-article.yaml
  /lodge-admin/article/{id}:
    put:
      path: queries/article/lodge-admin/l-aupdate-article.yaml
    delete:
      path: queries/article/lodge-admin/l-adelete-article.yaml
  /lodge-admin/event:
    get:
      path: queries/event/lodge-admin/l-aget-events.yaml
    post:
      path: queries/event/lodge-admin/l-aadd-event.yaml
  /lodge-admin/event/{id}:
    put:
      path: queries/event/lodge-admin/l-aupdate-event.yaml
    delete:
      path: queries/event/lodge-admin/l-adelete-event.yaml
  /lodge-admin/event/{eventId}/attendance:
    get:
      path: queries/event/lodge-admin/l-aget-attendance.yaml
    post:
      path: queries/event/lodge-admin/l-aadd-attendance.yaml
    put:
      path: queries/event/lodge-admin/l-aupdate-attendance.yaml
  /lodge-admin/event/{eventId}/attendance/{attendanceId}:
    put:
      path: queries/event/lodge-admin/l-aupdate-attendance-item.yaml
  /lodge-admin/contribution:
    get:
      path: queries/contribution/lodge-admin/l-alist-contributions.yaml
    post:
      path: queries/contribution/lodge-admin/l-aadd-contribution.yaml
  /lodge-admin/contribution/{id}:
    put:
      path: queries/contribution/lodge-admin/l-aupdate-contribution.yaml
    delete:
      path: queries/contribution/lodge-admin/l-aremove-contribution.yaml
  /lodge-admin/payment:
    get:
      path: queries/payment/lodge-admin/l-alist-payments.yaml
    post:
      path: queries/payment/lodge-admin/l-aadd-payment.yaml
  /lodge-admin/payment/{id}:
    put:
      path: queries/payment/lodge-admin/l-aupdate-payment.yaml
  /lodge-admin/user-contribution:
    get:
      path: queries/payment/lodge-admin/l-alist-user-contributions.yaml
    put:
      path: queries/payment/lodge-admin/l-aupdate-user-contributions.yaml
  /order-admin/article:
    get:
      path: queries/article/order-admin/o-aget-articles.yaml
    post:
      path: queries/article/order-admin/o-aadd-article.yaml
  /order-admin/article/{id}:
    put:
      path: queries/article/order-admin/o-aupdate-article.yaml
    delete:
      path: queries/article/order-admin/o-adelete-article.yaml
  /order-admin/audit:
    get:
      path: queries/audit/order-admin/o-aget-audit.yaml
  /order-admin/user:
    get:
      path: queries/user/order-admin/o-aget-users.yaml
    post:
      path: queries/user/order-admin/o-aadd-user.yaml
    put:
      path: queries/user/order-admin/o-aupload-users.yaml
  /order-admin/user/{id}:
    put:
      path: queries/user/order-admin/o-aupdate-user.yaml
    delete:
      path: queries/user/order-admin/o-adelete-user.yaml
  /order-admin/user/{userId}/history:
    get:
      path: queries/user/order-admin/o-aget-user-history.yaml
    post:
      path: queries/user/order-admin/o-aadd-user-history.yaml
  /order-admin/user/{userId}/history/{id}:
    put:
      path: queries/user/order-admin/o-aupdate-user-history.yaml
    delete:
      path: queries/user/order-admin/o-adelete-user-history.yaml
  /order-admin/event:
    get:
      path: queries/event/order-admin/o-aget-events.yaml
    post:
      path: queries/event/order-admin/o-aadd-event.yaml
  /order-admin/event/{id}:
    put:
      path: queries/event/order-admin/o-aupdate-event.yaml
    delete:
      path: queries/event/order-admin/o-adelete-event.yaml
  /order-admin/event/{eventId}/attendance:
    get:
      path: queries/event/order-admin/o-aget-attendance.yaml
    post:
      path: queries/event/order-admin/o-aadd-attendance.yaml
    put:
      path: queries/event/order-admin/o-aupdate-attendance.yaml
  /order-admin/event/{eventId}/attendance/{attendanceId}:
    put:
      path: queries/event/order-admin/o-aupdate-attendance-item.yaml
  /order-admin/lodge:
    get:
      path: queries/lodge/order-admin/o-aget-lodges.yaml
    post:
      path: queries/lodge/order-admin/o-aadd-lodge.yaml
  /order-admin/lodge/{id}:
    put:
      path: queries/lodge/order-admin/o-aupdate-lodge.yaml
    delete:
      path: queries/lodge/order-admin/o-adelete-lodge.yaml
  /order-admin/contribution:
    get:
      path: queries/contribution/order-admin/o-alist-contributions.yaml
    post:
      path: queries/contribution/order-admin/o-aadd-contribution.yaml
  /order-admin/contribution/{id}:
    put:
      path: queries/contribution/order-admin/o-aupdate-contribution.yaml
    delete:
      path: queries/contribution/order-admin/o-aremove-contribution.yaml
  /order-admin/payment:
    get:
      path: queries/payment/order-admin/o-alist-payments.yaml
    post:
      path: queries/payment/order-admin/o-aadd-payment.yaml
  /order-admin/payment/{id}:
    put:
      path: queries/payment/order-admin/o-aupdate-payment.yaml
  /order-admin/user-contribution:
    get:
      path: queries/payment/order-admin/o-alist-user-contributions.yaml
    put:
      path: queries/payment/order-admin/o-aupdate-user-contributions.yaml
  /order-admin/template:
    get:
      path: queries/template/order-admin/o-aget-templates.yaml
    post:
      path: queries/template/order-admin/o-aadd-template.yaml
  /order-admin/template/{id}:
    put:
      path: queries/template/order-admin/o-aupdate-template.yaml
    delete:
      path: queries/template/order-admin/o-adelete-template.yaml
    post:
      path: queries/template/order-admin/o-arender-template.yaml
