version: 0.0.1
dbConnection:
    type: postgres
    database: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
migrations: 
  - id: 001_initial
    applyPath: migrations/001_initial.sql
    rollbackPath: migrations/001_initial_rollback.sql
apiPath: ../mark-api.yaml

methodPaths:
  /public/article:
    get:
      path: queries/article/public/get-articles.yaml
  /regular-user/article:
    get:
      path: queries/article/regular-user/get-articles.yaml
    post:
      path: queries/article/regular-user/add-article.yaml
  /regular-user/article/{id}:
    put:
      path: queries/article/regular-user/update-article.yaml
    delete:
      path: queries/article/regular-user/delete-article.yaml
  /regular-user/event:
    get:
      path: queries/event/regular-user/get-events.yaml
  /regular-user/me:
    get:
      path: queries/user/regular-user/my-profile.yaml
  /regular-user/goodstanding:
    get:
      path: queries/user/regular-user/download-good-standing.yaml
  /regular-user/me/lodge:
    get:
      path: queries/user/regular-user/my-lodges.yaml
  /regular-user/history:
    get:
      path: queries/user/regular-user/my-history.yaml
  /regular-user/contribution:
    get:
      path: queries/user/regular-user/my-contributions.yaml
  /regular-user/payment:
    get:
      path: queries/user/regular-user/my-payments.yaml
    post:
      path: queries/user/regular-user/add-payment.yaml
  /regular-user/rsvp/{code}:
    put:
      path: queries/event/regular-user/rsvp-event.yaml
  /regular-user/lodge:
    get:
      path: queries/lodge/regular-user/get-lodges.yaml
  /lodge-admin/article:
    get:
      path: queries/article/lodge-admin/get-articles.yaml
    post:
      path: queries/article/lodge-admin/add-article.yaml
  /lodge-admin/article/{id}:
    put:
      path: queries/article/lodge-admin/update-article.yaml
    delete:
      path: queries/article/lodge-admin/delete-article.yaml
  /lodge-admin/event:
    get:
      path: queries/event/lodge-admin/get-events.yaml
    post:
      path: queries/event/lodge-admin/add-event.yaml
  /lodge-admin/event/{id}:
    put:
      path: queries/event/lodge-admin/update-event.yaml
    delete:
      path: queries/event/lodge-admin/delete-event.yaml
  /lodge-admin/event/{eventId}/attendance:
    get:
      path: queries/event/lodge-admin/get-attendance.yaml
    post:
      path: queries/event/lodge-admin/add-attendance.yaml
    put:
      path: queries/event/lodge-admin/update-attendance.yaml
  /lodge-admin/event/{eventId}/attendance/{id}:
    put:
      path: queries/event/lodge-admin/update-attendance-item.yaml
  /lodge-admin/contribution:
    get:
      path: queries/contribution/lodge-admin/list-contributions.yaml
    post:
      path: queries/contribution/lodge-admin/add-contribution.yaml
  /lodge-admin/contribution/{id}:
    put:
      path: queries/contribution/lodge-admin/update-contribution.yaml
    delete:
      path: queries/contribution/lodge-admin/remove-contribution.yaml
  /lodge-admin/payment:
    get:
      path: queries/payment/lodge-admin/list-payments.yaml
    post:
      path: queries/payment/lodge-admin/add-payment.yaml
  /lodge-admin/payment/{id}:
    put:
      path: queries/payment/lodge-admin/update-payment.yaml
  /lodge-admin/user-contribution:
    get:
      path: queries/payment/lodge-admin/list-user-contributions.yaml
    put:
      path: queries/payment/lodge-admin/update-user-contributions.yaml
  /order-admin/article:
    get:
      path: queries/article/order-admin/get-articles.yaml
    post:
      path: queries/article/order-admin/add-article.yaml
  /order-admin/article/{id}:
    put:
      path: queries/article/order-admin/update-article.yaml
    delete:
      path: queries/article/order-admin/delete-article.yaml
  /order-admin/audit:
    get:
      path: queries/audit/order-admin/get-audit.yaml
  /order-admin/user:
    get:
      path: queries/user/order-admin/get-users.yaml
    post:
      path: queries/user/order-admin/add-user.yaml
    put:
      path: queries/user/order-admin/upload-users.yaml
  /order-admin/user/{id}:
    put:
      path: queries/user/order-admin/update-user.yaml
    delete:
      path: queries/user/order-admin/delete-user.yaml
  /order-admin/user/{userId}/history:
    get:
      path: queries/user/order-admin/get-user-history.yaml
    post:
      path: queries/user/order-admin/add-user-history.yaml
  /order-admin/user/{userId}/history/{id}:
    put:
      path: queries/user/order-admin/update-user-history.yaml
    delete:
      path: queries/user/order-admin/delete-user-history.yaml
  /order-admin/event:
    get:
      path: queries/event/order-admin/get-events.yaml
    post:
      path: queries/event/order-admin/add-event.yaml
  /order-admin/event/{id}:
    put:
      path: queries/event/order-admin/update-event.yaml
    delete:
      path: queries/event/order-admin/delete-event.yaml
  /order-admin/event/{eventId}/attendance:
    get:
      path: queries/event/order-admin/get-attendance.yaml
    post:
      path: queries/event/order-admin/add-attendance.yaml
    put:
      path: queries/event/order-admin/update-attendance.yaml
  /order-admin/event/{eventId}/attendance/{id}:
    put:
      path: queries/event/order-admin/update-attendance-item.yaml
  /order-admin/lodge:
    get:
      path: queries/lodge/order-admin/get-lodges.yaml
    post:
      path: queries/lodge/order-admin/add-lodge.yaml
  /order-admin/lodge/{id}:
    put:
      path: queries/lodge/order-admin/update-lodge.yaml
    delete:
      path: queries/lodge/order-admin/delete-lodge.yaml
  /order-admin/contribution:
    get:
      path: queries/contribution/order-admin/list-contributions.yaml
    post:
      path: queries/contribution/order-admin/add-contribution.yaml
  /order-admin/contribution/{id}:
    put:
      path: queries/contribution/order-admin/update-contribution.yaml
    delete:
      path: queries/contribution/order-admin/remove-contribution.yaml
  /order-admin/payment:
    get:
      path: queries/payment/order-admin/list-payments.yaml
    post:
      path: queries/payment/order-admin/add-payment.yaml
  /order-admin/payment/{id}:
    put:
      path: queries/payment/order-admin/update-payment.yaml
  /order-admin/user-contribution:
    get:
      path: queries/payment/order-admin/list-user-contributions.yaml
    put:
      path: queries/payment/order-admin/update-user-contributions.yaml
  /order-admin/template:
    get:
      path: queries/template/order-admin/get-templates.yaml
    post:
      path: queries/template/order-admin/add-template.yaml
  /order-admin/template/{id}:
    put:
      path: queries/template/order-admin/update-template.yaml
    delete:
      path: queries/template/order-admin/delete-template.yaml
    post:
      path: queries/template/order-admin/render-template.yaml
