apiVersion: v1
kind: Service
metadata:
  name: mark-fe-svc
  labels:
    {{- include "mark-helm.selectorLabels" . | nindent 8 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mark-fe
